# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import kafka_consumer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.BigIntegerField(null=True, verbose_name='Offset')),
                ('topic', models.CharField(max_length=255, unique=True, verbose_name='Topic')),
            ],
        ),
        migrations.CreateModel(
            name='JunkMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('subscriber', models.CharField(max_length=100, verbose_name='Subscriber')),
                ('raw_data', kafka_consumer.fields.Base64TextField(verbose_name='Raw data')),
                ('error_message', models.CharField(max_length=1000, verbose_name='Error message')),
                ('offset', models.BigIntegerField(verbose_name='Offset')),
                ('topic_key', models.CharField(max_length=100, verbose_name='Topic key')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
